#########################################
###          Main App config          ###
#########################################
template_version: 0.2

# Main server app name
app_name: rogerthat

# ADVANCED!
# Enabled debug mode
debug_mode: false
