#########################################
###        TradingView config         ###
#########################################
template_version: 0.3

# A list of fields or key names to be included in event broadcasts
tradingview_include_extra_fields:
- extra_data

# A list of fields or key names to be excluded from event broadcasts
tradingview_exclude_fields:
- exclude_this_key
