#########################################
###        TradingView config         ###
#########################################
template_version: 0.2

# A list of key names to use for the event descriptor on received events.
# Only one will be used.
# Event data must contain a descriptor key to be accepted.
tradingview_translations:
  name: translated_name
