"""Add is_raw_msg

Revision ID: 18981fafc674
Revises: d40b06f2cc82
Create Date: 2022-12-30 02:47:43.782191+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18981fafc674'
down_revision = 'd40b06f2cc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('is_raw_msg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradingview_events', 'is_raw_msg')
    # ### end Alembic commands ###
