"""Add Additional Order Fields

Revision ID: 49158b1dc3fa
Revises: bfcd5d46d41a
Create Date: 2021-09-27 08:06:12.484608+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49158b1dc3fa'
down_revision = 'bfcd5d46d41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('order_bid_spread', sa.Numeric(), nullable=True))
    op.add_column('tradingview_events', sa.Column('order_ask_spread', sa.Numeric(), nullable=True))
    op.add_column('tradingview_events', sa.Column('order_amount', sa.Numeric(), nullable=True))
    op.add_column('tradingview_events', sa.Column('order_levels', sa.Numeric(), nullable=True))
    op.add_column('tradingview_events', sa.Column('order_level_spread', sa.Numeric(), nullable=True))
    op.create_index(op.f('ix_tradingview_events_order_amount'), 'tradingview_events', ['order_amount'], unique=False)
    op.create_index(op.f('ix_tradingview_events_order_ask_spread'), 'tradingview_events', ['order_ask_spread'], unique=False)
    op.create_index(op.f('ix_tradingview_events_order_bid_spread'), 'tradingview_events', ['order_bid_spread'], unique=False)
    op.create_index(op.f('ix_tradingview_events_order_level_spread'), 'tradingview_events', ['order_level_spread'], unique=False)
    op.create_index(op.f('ix_tradingview_events_order_levels'), 'tradingview_events', ['order_levels'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradingview_events_order_levels'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_order_level_spread'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_order_bid_spread'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_order_ask_spread'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_order_amount'), table_name='tradingview_events')
    op.drop_column('tradingview_events', 'order_level_spread')
    op.drop_column('tradingview_events', 'order_levels')
    op.drop_column('tradingview_events', 'order_amount')
    op.drop_column('tradingview_events', 'order_ask_spread')
    op.drop_column('tradingview_events', 'order_bid_spread')
    # ### end Alembic commands ###
