"""switch to topic from event_descriptor

Revision ID: b492ff9dde0a
Revises: 49158b1dc3fa
Create Date: 2022-12-24 17:34:05.168925+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b492ff9dde0a'
down_revision = '49158b1dc3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('topic', sa.String(length=220), nullable=True))
    op.drop_index('ix_tradingview_events_event_descriptor', table_name='tradingview_events')
    op.create_index(op.f('ix_tradingview_events_topic'), 'tradingview_events', ['topic'], unique=False)
    op.drop_column('tradingview_events', 'event_descriptor')
    op.execute("delete from tradingview_events")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('event_descriptor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tradingview_events_topic'), table_name='tradingview_events')
    op.create_index('ix_tradingview_events_event_descriptor', 'tradingview_events', ['event_descriptor'], unique=False)
    op.drop_column('tradingview_events', 'topic')
    # ### end Alembic commands ###
