"""more mqtt refactoring

Revision ID: d40b06f2cc82
Revises: d70319712f5b
Create Date: 2022-12-29 03:29:15.752967+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd40b06f2cc82'
down_revision = 'd70319712f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('sequence', sa.BigInteger(), nullable=True))
    op.add_column('tradingview_events', sa.Column('event_type', sa.String(length=90), nullable=True))
    op.add_column('tradingview_events', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tradingview_events', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tradingview_events', sa.Column('msg', sa.String(length=500), nullable=True))
    op.add_column('tradingview_events', sa.Column('log_level', sa.String(length=30), nullable=True))
    op.add_column('tradingview_events', sa.Column('restore', sa.Boolean(), nullable=True))
    op.add_column('tradingview_events', sa.Column('script', sa.String(length=90), nullable=True))
    op.add_column('tradingview_events', sa.Column('is_quickstart', sa.Boolean(), nullable=True))
    op.add_column('tradingview_events', sa.Column('skip_order_cancellation', sa.Boolean(), nullable=True))
    op.add_column('tradingview_events', sa.Column('strategy', sa.String(length=90), nullable=True))
    op.add_column('tradingview_events', sa.Column('days', sa.Numeric(), nullable=True))
    op.add_column('tradingview_events', sa.Column('verbose', sa.Boolean(), nullable=True))
    op.add_column('tradingview_events', sa.Column('precision', sa.Integer(), nullable=True))
    op.drop_index('ix_tradingview_events_command', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_interval', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_inventory', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_order_amount', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_order_ask_spread', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_order_bid_spread', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_order_level_spread', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_order_levels', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_price', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_symbol', table_name='tradingview_events')
    op.drop_index('ix_tradingview_events_volume', table_name='tradingview_events')
    op.create_index(op.f('ix_tradingview_events_event_type'), 'tradingview_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tradingview_events_sequence'), 'tradingview_events', ['sequence'], unique=False)
    op.create_index(op.f('ix_tradingview_events_strategy'), 'tradingview_events', ['strategy'], unique=False)
    op.drop_column('tradingview_events', 'interval')
    op.drop_column('tradingview_events', 'order_bid_spread')
    op.drop_column('tradingview_events', 'inventory')
    op.drop_column('tradingview_events', 'volume')
    op.drop_column('tradingview_events', 'order_ask_spread')
    op.drop_column('tradingview_events', 'price')
    op.drop_column('tradingview_events', 'order_level_spread')
    op.drop_column('tradingview_events', 'symbol')
    op.drop_column('tradingview_events', 'order_levels')
    op.drop_column('tradingview_events', 'command')
    op.drop_column('tradingview_events', 'order_amount')
    op.execute("delete from tradingview_events")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('order_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('command', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('order_levels', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('order_level_spread', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('order_ask_spread', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('volume', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('inventory', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('order_bid_spread', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tradingview_events', sa.Column('interval', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tradingview_events_strategy'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_sequence'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_event_type'), table_name='tradingview_events')
    op.create_index('ix_tradingview_events_volume', 'tradingview_events', ['volume'], unique=False)
    op.create_index('ix_tradingview_events_symbol', 'tradingview_events', ['symbol'], unique=False)
    op.create_index('ix_tradingview_events_price', 'tradingview_events', ['price'], unique=False)
    op.create_index('ix_tradingview_events_order_levels', 'tradingview_events', ['order_levels'], unique=False)
    op.create_index('ix_tradingview_events_order_level_spread', 'tradingview_events', ['order_level_spread'], unique=False)
    op.create_index('ix_tradingview_events_order_bid_spread', 'tradingview_events', ['order_bid_spread'], unique=False)
    op.create_index('ix_tradingview_events_order_ask_spread', 'tradingview_events', ['order_ask_spread'], unique=False)
    op.create_index('ix_tradingview_events_order_amount', 'tradingview_events', ['order_amount'], unique=False)
    op.create_index('ix_tradingview_events_inventory', 'tradingview_events', ['inventory'], unique=False)
    op.create_index('ix_tradingview_events_interval', 'tradingview_events', ['interval'], unique=False)
    op.create_index('ix_tradingview_events_command', 'tradingview_events', ['command'], unique=False)
    op.drop_column('tradingview_events', 'precision')
    op.drop_column('tradingview_events', 'verbose')
    op.drop_column('tradingview_events', 'days')
    op.drop_column('tradingview_events', 'strategy')
    op.drop_column('tradingview_events', 'skip_order_cancellation')
    op.drop_column('tradingview_events', 'is_quickstart')
    op.drop_column('tradingview_events', 'script')
    op.drop_column('tradingview_events', 'restore')
    op.drop_column('tradingview_events', 'log_level')
    op.drop_column('tradingview_events', 'msg')
    op.drop_column('tradingview_events', 'data')
    op.drop_column('tradingview_events', 'params')
    op.drop_column('tradingview_events', 'event_type')
    op.drop_column('tradingview_events', 'sequence')
    # ### end Alembic commands ###
