"""Add amount and asset fields

Revision ID: d70319712f5b
Revises: b492ff9dde0a
Create Date: 2022-12-25 03:58:56.086134+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70319712f5b'
down_revision = 'b492ff9dde0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingview_events', sa.Column('asset', sa.String(length=30), nullable=True))
    op.add_column('tradingview_events', sa.Column('amount', sa.Numeric(), nullable=True))
    op.create_index(op.f('ix_tradingview_events_amount'), 'tradingview_events', ['amount'], unique=False)
    op.create_index(op.f('ix_tradingview_events_asset'), 'tradingview_events', ['asset'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradingview_events_asset'), table_name='tradingview_events')
    op.drop_index(op.f('ix_tradingview_events_amount'), table_name='tradingview_events')
    op.drop_column('tradingview_events', 'amount')
    op.drop_column('tradingview_events', 'asset')
    # ### end Alembic commands ###
